appenders:
  stdout_logger:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  file_logger:
      kind: rolling_file
      path: "log/application.log"
      encoder:
        pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
      policy:
        trigger:
          kind: size
          limit: 100kb
        roller:
          kind: delete
root:
  level: info
  appenders:
    - stdout_logger
    - file_logger

